import { Project, Tags, Stack } from "@/types/types";

export const works: Project[] = [
  {
    name: "Ecobit",
    image: "/ecobit.png",
    description: "",
    domain: "www.rustore.ru/catalog/app/com.fcore.ecobit",
    stack: [],
    screenshots: [],
    video: [],
    id: 1,
    tags: [Tags.MOBILE, Tags.FIN],
  },
  {
    name: "KingPay",
    image: "/kingpay.png",
    description:
      "Интернет эквайринг для приема и обработки платежей. Реализованное решение поддерживает следующие методы оплаты: СБП, Карта, Электронные кошельки, Мобильная коммерция. Используются, современные методы защиты информации",
    domain: "kingpay.space",
    stack: [
      { name: Stack.NEXT, image: "/next.png" },
      { name: Stack.SQL, image: "/postgres.png" },

      { name: Stack.Django, image: "/django.png" },
      { name: Stack.FIGMA, image: "/figma.png" },
      { name: Stack.REACT, image: "/react.png" },
    ],
    screenshots: [
      "/kingpay/first.png",
      "/kingpay/second.png",
      "/kingpay/third.png",
    ],
    video: [],
    id: 2,
    tags: [Tags.WEBAPP, Tags.FIN],
    stat1: "4",
    name1: "месяца работ",
    stat2: ">1000",
    name2: "довольных юзеров",
    stat3: "5.0",
    name3: "оценка клиента",
    stat4: "200k+",
    name4: "платежей",
    first_desc: `Клиент пришел с задачей: разработать с нуля <span>Современный, безопасный и клиентоориентированный сайт</span> — это основной инструмент для привлечения, конвертации и удержания мерчантов в высококонкурентной нише fintech. <br/><br/>Основной бизнес-целью было увеличение конверсии в заявку на 25%.<br/> Маркетинговой — усиление позиционирования как безопасного и современного решения. <br>Пользовательской — создание ясного пути для разных типов клиентов. И<span> Именно Фкор<span/> взялась за реализацию этой идеи!`,
    second_desc: `С первых дней, наше агентство начало прорабатывать всю документацию будущего проекта, от и до. После утверждения технического задания, мы незамедлительно приступили к разработке макета и созднию серверной части,  <span>используя самые современные технологии </span> <br><br> Важнейшей частью работы являлась безопасность, важно, чтобы проект имел <span> максимальные стандарты безопасности </span>, а пользователи не теряли свои деньги в резульатате хакерских атак. Мы использовали различные алгоритмы защиты на проекте: PCI DSS, HTTPS, UUID-V4, SecretKeys. <br><br> В конце разработки <span>клиент был макисмально доволен преоктом</span>, наше агентство завершило работу над платежной системой с опережением срока и успешно запустило её!`,
    image1: "/lk_kingpay.png",
    image2: "/lk_kingpay2.png",
  },
  {
    name: "LiteStore",
    image: "/litestore.png",
    description: "",
    domain: "это дизайн",
    stack: [],
    screenshots: [],
    video: [],
    id: 3,
    tags: [Tags.DES, Tags.ECOM],
  },
  {
    name: "StonTactics",
    image: "/stontactics.png",
    description: "",
    domain: "stontactics.ru",
    stack: [],
    screenshots: [],
    video: [],
    id: 4,
    tags: [Tags.WEBAPP, Tags.GAME],
  },
  {
    name: "CityHome",
    image: "/cityhome.png",
    description: "",
    domain: "это дизайн",
    stack: [],
    screenshots: [],
    video: [],
    id: 5,
    tags: [Tags.LAND, Tags.DES],
  },
  {
    name: "Najd",
    image: "/parfume.png",
    description: "",
    domain: "mylabparfume.com",
    stack: [],
    screenshots: [],
    video: [],
    id: 6,
    tags: [Tags.LAND, Tags.BRAND],
  },

  {
    name: "PicLoad",
    image: "/picload.png",
    description: "",
    domain: "@picload_bot",
    stack: [],
    screenshots: [],
    video: [],
    id: 7,
    tags: [Tags.LAND, Tags.BRAND],
  },
  {
    name: "Тройка групп",
    image: "/troika.png",
    description: "",
    domain: "troikagroup.pro",
    stack: [],
    screenshots: [],
    video: [],
    id: 8,
    tags: [Tags.WEBAPP, Tags.FIN],
  },
  {
    name: "Игра Золтана",
    image: "/zoltansgame.png",
    description: "",
    domain: "igrazoltana.ru",
    stack: [],
    screenshots: [],
    video: [],
    id: 9,
    tags: [Tags.WEBAPP, Tags.GAME],
  },
  {
    name: "Бал Кекина",
    image: "/kekin.png",
    description: "",
    domain: "bal-kekina.ru",
    stack: [],
    screenshots: [],
    video: [],
    id: 10,
    tags: [Tags.WEBAPP, Tags.EVENT],
  },
  {
    name: "Судэкспертиза Беларусь",
    image: "/sudmed.png",
    description: "",
    domain: "Недоступно",
    stack: [],
    screenshots: [],
    video: [],
    id: 11,
    tags: [Tags.WEBAPP, Tags.GOV],
  },
];
