import { Project, Tags } from "@/types/types";

export const works: Project[] = [
  {
    name: "Ecobit",
    image: "/ecobit.png",
    description: "",
    domain: "www.rustore.ru/catalog/app/com.fcore.ecobit",
    stack: [],
    screenshots: [],
    video: [],
    id: 1,
    tags: [Tags.MOBILE, Tags.FIN],
  },
  {
    name: "KingPay",
    image: "/kingpay.png",
    description:
      "KingPay - интернет эквайринг для приема и обработки платежей. Реализованное решение поддерживает следующие методы оплаты: СБП, Карта, Электронные кошельки, Мобильная коммерция.",
    domain: "kingpay.space",
    stack: [],
    screenshots: [
      "/kingpay/first.png",
      "/kingpay/second.png",
      "/kingpay/third.png",
    ],
    video: [],
    id: 2,
    tags: [Tags.WEBAPP, Tags.FIN],
  },
  {
    name: "Najd",
    image: "/parfume.png",
    description: "",
    domain: "mylabparfume.com",
    stack: [],
    screenshots: [],
    video: [],
    id: 3,
    tags: [Tags.LAND, Tags.BRAND],
  },
  {
    name: "Тройка групп",
    image: "/troika.png",
    description: "",
    domain: "troika-group.com",
    stack: [],
    screenshots: [],
    video: [],
    id: 4,
    tags: [Tags.WEBAPP, Tags.FIN],
  },
  {
    name: "ДокМобиль",
    image: "/docmobile.png",
    description: "",
    domain: "это дизайн",
    stack: [],
    screenshots: [],
    video: [],
    id: 5,
    tags: [Tags.DES, Tags.BRAND],
  },
  {
    name: "Игра Золтана",
    image: "/zoltansgame.png",
    description: "",
    domain: "igrazoltana.ru",
    stack: [],
    screenshots: [],
    video: [],
    id: 6,
    tags: [Tags.WEBAPP, Tags.GAME],
  },
  {
    name: "Бал Кекина",
    image: "/kekin.png",
    description: "",
    domain: "bal-kekina.ru",
    stack: [],
    screenshots: [],
    video: [],
    id: 7,
    tags: [Tags.WEBAPP, Tags.EVENT],
  },
  {
    name: "Судэкспертиза Беларусь",
    image: "/sudmed.png",
    description: "",
    domain: "Недоступно",
    stack: [],
    screenshots: [],
    video: [],
    id: 8,
    tags: [Tags.WEBAPP, Tags.GOV],
  },
];
